#!/bin/bash
CURR_DIR=$(pwd)
SCRIPT_DIR="$CURR_DIR/$(dirname "$0")"
cd $SCRIPT_DIR
export CXX=g++
export CC=gcc

# Uncomment the libs that you added and customize paths if necessary
#BLOSSOM_V_DIR=blossom-v
#BLOSSOM_IV_DIR=blossom-iv
#LEMON_DIR=lemon-1.3.1
#FADE_DIR=fadeRelease_v1.74
#FADE_LIB_DIR=lib_ubuntu18.04_x86_64
#FADE_LIB_NAME=fade2d

#cmake -DCMAKE_BUILD_TYPE=Release -DBLOSSOM_V_DIR=$BLOSSOM_V_DIR -DBLOSSOM_IV_DIR=$BLOSSOM_IV_DIR -DLEMON_DIR=$LEMON_DIR -DFADE_DIR=$FADE_DIR -DFADE_LIB_DIR=$FADE_LIB_DIR -DFADE_LIB_NAME=$FADE_LIB_NAME .
cmake -DCMAKE_BUILD_TYPE=Debug -DBLOSSOM_V_DIR=$BLOSSOM_V_DIR -DBLOSSOM_IV_DIR=$BLOSSOM_IV_DIR -DLEMON_DIR=$LEMON_DIR -DFADE_DIR=$FADE_DIR -DFADE_LIB_DIR=$FADE_LIB_DIR -DFADE_LIB_NAME=$FADE_LIB_NAME .
make
cd $CURR_DIR
